name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # O la rama que prefieras

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.REGION }} # Cambia esto a tu región preferida
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Autenticación con Google Cloud
      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Configurar Docker para Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # # Construir y empujar la imagen usando Github actions
      - name: Build and Push Container
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t $DOCKER_TAG .
          docker push $DOCKER_TAG
      # - name: Build and Push with Cloud Build
      #   run: |-
      #     gcloud builds submit --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      # Desplegar en Cloud Run
      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: "--allow-unauthenticated" # Opcional: para que sea público
